excluded: # do not run swiftlint on pods
  - Pods
  - CombMe/Config/Swiftgen
  - CombMe/AppDelegate/AppDelegate.swift
variable_name: #exclude variables from naming rules
  excluded:
    - vc # variable used by apple internally
    - id
    - ID
    - example

line_length: 120 # set maximum line length
type_body_length: 680 # set maximum type body length
file_length: 680 # set maximum file line length
function_parameter_count: 10 # set maximum function parameter count
cyclomatic_complexity: 15 # set maximum cyclomatic complexity

disabled_rules: # rule identifiers to disable globally
# all rules: https://github.com/realm/SwiftLint/tree/master/Source/SwiftLintFramework/Rules

custom_rules:
  dont_use_print: # rule identifier
    name: "Do not use the default print method" # rule name. optional.
    regex: 'print\(' # matching pattern
    match_kinds: # SyntaxKinds to match. optional.
      - comment
      - identifier
    message:'Use debugPrint("File:\(#file), Function:\(#function), Line: \(#line)" + "place param here")' # violation message. optional.
    severity: error # violation severity. optional.
